# This is a basic workflow to help you get started with Actions

name: Call a reusable workflow and use its outputs

# Controls when the workflow will run
on:
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    uses: Sneha123-star/git_1/.github/workflows/ci.yml@main
    with:
         username: sneha
         repo_name: Sneha123-star/task1_repo
         repo_path: Sneha123-star/task1_repo
