# This is a basic workflow to help you get started with Actions

name: Call a reusable workflow and use its outputs

# Controls when the workflow will run
on:
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    uses: Sneha123-star/git_1/.github/workflows/ci.yml@main
    with:
         username: sneha
         #repo_path: Sneha123-star/task1_repo
  example_job2:
    name: Pass file
    runs-on: windows-latest
    steps:
     - name: checkout
       uses: actions/checkout@v2
       #with:
        #repository: ${{ inputs.repo_path }}
        #path: ${{ inputs.repo_name }}
     - name: setup python
       uses: actions/setup-python@v2
       with:
          python-version: 3.8 #install the python needed
     - name: execute py script # run the run.py to get the latest data
       run: |
          python main.py 
